version: '3.8'
services:
  dynamo:
    command: -jar DynamoDBLocal.jar -sharedDb
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-auditor
    ports:
      - 28000:8000
  mysql:
    image: mysql:8.1.0  # You can use a different MySQL version if needed
    container_name: my-mysql-container  # Give your container a unique name
    environment:
      MYSQL_ROOT_PASSWORD: root1  # Change this to your desired root password
      MYSQL_DATABASE: test  # Change this to your desired database name
      MYSQL_USER: root2  # Change this to your desired MySQL user
      MYSQL_PASSWORD: root3  # Change this to your desired MySQL user's password
    ports:
      - 3306:3306  # You can change the host port if necessary
    volumes:
      - /tmp/mysql-data:/var/lib/mysql  # Persist MySQL data on your host machine
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /tmp/data:/data/db    
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
